### PR TITLE
convert to ESM

### PR DESCRIPTION
**Pull request by hatemhosny**
Nice work 👍

this is a trivial PR to convert it to ES module.

I noticed you import it as ES module for usage:
https://codesandbox.io/p/sandbox/using-foxrandomstring-55h27v?file=%2Fsrc%2Findex.js%3A1%2C51

you can try it on LiveCodes:
https://livecodes.io/?x=id/atvgvem2fuj

by the way, I invite you to try LiveCodes which is a [feature-rich](https://livecodes.io/docs/features/), open-source, client-side code playground for React, Vue, Svelte, Solid, Typescript, Python, Go, Ruby, PHP and [80+ languages/frameworks](https://livecodes.io/docs/languages/). You can easily [share](https://livecodes.io/docs/features/share) projects and [embed](https://livecodes.io/docs/features/embeds) them in web pages.
App: https://livecodes.io/
Docs: https://livecodes.io/docs/
GitHub: https://github.com/live-codes/livecodes

### CODE REVIEW

**Comment by saidbakr** [comment]
Thank you for the contribution. It has been merged.

**Comment by hatemhosny** [comment]
Thank you :)

You can try it now like this:
https://livecodes.io/?x=id/ubvauuq5an7

**Comment by saidbakr** [comment]
The external resources in livecodes does not able to find any npm package.
image

**Comment by hatemhosny** [comment]
I just tested it. May be it was a network connection problem.

Please let me know if you still have problems

Screenshot (14)

**Pull request merged**
